'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("3458c296-7cb3-4869-a0be-0472f313e12b")> 

'Original file name:
'Generation date: 23/11/2015 2:28:38 PM
'''<summary>
'''There are no comments for FAMEntities in the schema.
'''</summary>
Partial Public Class FAMEntities
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new FAMEntities object using the connection string found in the 'FAMEntities' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=FAMEntities", "FAMEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new FAMEntities object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "FAMEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new FAMEntities object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "FAMEntities")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for CG_Voucher_Detail in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property CG_Voucher_Detail() As Global.System.Data.Objects.ObjectQuery(Of CG_Voucher_Detail)
        Get
            If (Me._CG_Voucher_Detail Is Nothing) Then
                Me._CG_Voucher_Detail = MyBase.CreateQuery(Of CG_Voucher_Detail)("[CG_Voucher_Detail]")
            End If
            Return Me._CG_Voucher_Detail
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _CG_Voucher_Detail As Global.System.Data.Objects.ObjectQuery(Of CG_Voucher_Detail)
    '''<summary>
    '''There are no comments for CG_Voucher_Detail in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToCG_Voucher_Detail(ByVal cG_Voucher_Detail As CG_Voucher_Detail)
        MyBase.AddObject("CG_Voucher_Detail", cG_Voucher_Detail)
    End Sub
End Class
'''<summary>
'''There are no comments for FAMModel.CG_Voucher_Detail in the schema.
'''</summary>
'''<KeyProperties>
'''VD_Fin_Yr
'''VD_Inst_Cd
'''VD_Inst_Typ
'''VD_Brn_Cd
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="FAMModel", Name:="CG_Voucher_Detail"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class CG_Voucher_Detail
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new CG_Voucher_Detail object.
    '''</summary>
    '''<param name="vD_Fin_Yr">Initial value of VD_Fin_Yr.</param>
    '''<param name="vD_Inst_Cd">Initial value of VD_Inst_Cd.</param>
    '''<param name="vD_Inst_Typ">Initial value of VD_Inst_Typ.</param>
    '''<param name="vD_Brn_Cd">Initial value of VD_Brn_Cd.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateCG_Voucher_Detail(ByVal vD_Fin_Yr As String, ByVal vD_Inst_Cd As String, ByVal vD_Inst_Typ As String, ByVal vD_Brn_Cd As String) As CG_Voucher_Detail
        Dim cG_Voucher_Detail As CG_Voucher_Detail = New CG_Voucher_Detail()
        cG_Voucher_Detail.VD_Fin_Yr = vD_Fin_Yr
        cG_Voucher_Detail.VD_Inst_Cd = vD_Inst_Cd
        cG_Voucher_Detail.VD_Inst_Typ = vD_Inst_Typ
        cG_Voucher_Detail.VD_Brn_Cd = vD_Brn_Cd
        Return cG_Voucher_Detail
    End Function
    '''<summary>
    '''There are no comments for property VD_Fin_Yr in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Fin_Yr() As String
        Get
            Return Me._VD_Fin_Yr
        End Get
        Set
            Me.OnVD_Fin_YrChanging(value)
            Me.ReportPropertyChanging("VD_Fin_Yr")
            Me._VD_Fin_Yr = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("VD_Fin_Yr")
            Me.OnVD_Fin_YrChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Fin_Yr As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Fin_YrChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Fin_YrChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Inst_Cd in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Inst_Cd() As String
        Get
            Return Me._VD_Inst_Cd
        End Get
        Set
            Me.OnVD_Inst_CdChanging(value)
            Me.ReportPropertyChanging("VD_Inst_Cd")
            Me._VD_Inst_Cd = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("VD_Inst_Cd")
            Me.OnVD_Inst_CdChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Inst_Cd As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Inst_CdChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Inst_CdChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Inst_Typ in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Inst_Typ() As String
        Get
            Return Me._VD_Inst_Typ
        End Get
        Set
            Me.OnVD_Inst_TypChanging(value)
            Me.ReportPropertyChanging("VD_Inst_Typ")
            Me._VD_Inst_Typ = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("VD_Inst_Typ")
            Me.OnVD_Inst_TypChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Inst_Typ As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Inst_TypChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Inst_TypChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Brn_Cd in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Brn_Cd() As String
        Get
            Return Me._VD_Brn_Cd
        End Get
        Set
            Me.OnVD_Brn_CdChanging(value)
            Me.ReportPropertyChanging("VD_Brn_Cd")
            Me._VD_Brn_Cd = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("VD_Brn_Cd")
            Me.OnVD_Brn_CdChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Brn_Cd As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Brn_CdChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Brn_CdChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Lnk_No in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Lnk_No() As String
        Get
            Return Me._VD_Lnk_No
        End Get
        Set
            Me.OnVD_Lnk_NoChanging(value)
            Me.ReportPropertyChanging("VD_Lnk_No")
            Me._VD_Lnk_No = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Lnk_No")
            Me.OnVD_Lnk_NoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Lnk_No As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Lnk_NoChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Lnk_NoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Dbk_Cd in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Dbk_Cd() As String
        Get
            Return Me._VD_Dbk_Cd
        End Get
        Set
            Me.OnVD_Dbk_CdChanging(value)
            Me.ReportPropertyChanging("VD_Dbk_Cd")
            Me._VD_Dbk_Cd = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Dbk_Cd")
            Me.OnVD_Dbk_CdChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Dbk_Cd As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Dbk_CdChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Dbk_CdChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Trn_Typ in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Trn_Typ() As String
        Get
            Return Me._VD_Trn_Typ
        End Get
        Set
            Me.OnVD_Trn_TypChanging(value)
            Me.ReportPropertyChanging("VD_Trn_Typ")
            Me._VD_Trn_Typ = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Trn_Typ")
            Me.OnVD_Trn_TypChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Trn_Typ As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Trn_TypChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Trn_TypChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Vch_No in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Vch_No() As String
        Get
            Return Me._VD_Vch_No
        End Get
        Set
            Me.OnVD_Vch_NoChanging(value)
            Me.ReportPropertyChanging("VD_Vch_No")
            Me._VD_Vch_No = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Vch_No")
            Me.OnVD_Vch_NoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Vch_No As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Vch_NoChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Vch_NoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Vch_Ref_No in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Vch_Ref_No() As String
        Get
            Return Me._VD_Vch_Ref_No
        End Get
        Set
            Me.OnVD_Vch_Ref_NoChanging(value)
            Me.ReportPropertyChanging("VD_Vch_Ref_No")
            Me._VD_Vch_Ref_No = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Vch_Ref_No")
            Me.OnVD_Vch_Ref_NoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Vch_Ref_No As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Vch_Ref_NoChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Vch_Ref_NoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Seq_No in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Seq_No() As String
        Get
            Return Me._VD_Seq_No
        End Get
        Set
            Me.OnVD_Seq_NoChanging(value)
            Me.ReportPropertyChanging("VD_Seq_No")
            Me._VD_Seq_No = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Seq_No")
            Me.OnVD_Seq_NoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Seq_No As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Seq_NoChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Seq_NoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Ref_No in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Ref_No() As String
        Get
            Return Me._VD_Ref_No
        End Get
        Set
            Me.OnVD_Ref_NoChanging(value)
            Me.ReportPropertyChanging("VD_Ref_No")
            Me._VD_Ref_No = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Ref_No")
            Me.OnVD_Ref_NoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Ref_No As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Ref_NoChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Ref_NoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Ref_Dt in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Ref_Dt() As Global.System.Nullable(Of Date)
        Get
            Return Me._VD_Ref_Dt
        End Get
        Set
            Me.OnVD_Ref_DtChanging(value)
            Me.ReportPropertyChanging("VD_Ref_Dt")
            Me._VD_Ref_Dt = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("VD_Ref_Dt")
            Me.OnVD_Ref_DtChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Ref_Dt As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Ref_DtChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Ref_DtChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Narr in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Narr() As String
        Get
            Return Me._VD_Narr
        End Get
        Set
            Me.OnVD_NarrChanging(value)
            Me.ReportPropertyChanging("VD_Narr")
            Me._VD_Narr = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Narr")
            Me.OnVD_NarrChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Narr As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_NarrChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_NarrChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Lgr_Cd in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Lgr_Cd() As String
        Get
            Return Me._VD_Lgr_Cd
        End Get
        Set
            Me.OnVD_Lgr_CdChanging(value)
            Me.ReportPropertyChanging("VD_Lgr_Cd")
            Me._VD_Lgr_Cd = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Lgr_Cd")
            Me.OnVD_Lgr_CdChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Lgr_Cd As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Lgr_CdChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Lgr_CdChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Acc_Cd in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Acc_Cd() As String
        Get
            Return Me._VD_Acc_Cd
        End Get
        Set
            Me.OnVD_Acc_CdChanging(value)
            Me.ReportPropertyChanging("VD_Acc_Cd")
            Me._VD_Acc_Cd = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Acc_Cd")
            Me.OnVD_Acc_CdChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Acc_Cd As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Acc_CdChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Acc_CdChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Amt in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Amt() As Global.System.Nullable(Of Decimal)
        Get
            Return Me._VD_Amt
        End Get
        Set
            Me.OnVD_AmtChanging(value)
            Me.ReportPropertyChanging("VD_Amt")
            Me._VD_Amt = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("VD_Amt")
            Me.OnVD_AmtChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Amt As Global.System.Nullable(Of Decimal)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_AmtChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_AmtChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Cr_Dr in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Cr_Dr() As String
        Get
            Return Me._VD_Cr_Dr
        End Get
        Set
            Me.OnVD_Cr_DrChanging(value)
            Me.ReportPropertyChanging("VD_Cr_Dr")
            Me._VD_Cr_Dr = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Cr_Dr")
            Me.OnVD_Cr_DrChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Cr_Dr As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Cr_DrChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Cr_DrChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_ABS_Amt in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_ABS_Amt() As Global.System.Nullable(Of Decimal)
        Get
            Return Me._VD_ABS_Amt
        End Get
        Set
            Me.OnVD_ABS_AmtChanging(value)
            Me.ReportPropertyChanging("VD_ABS_Amt")
            Me._VD_ABS_Amt = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("VD_ABS_Amt")
            Me.OnVD_ABS_AmtChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_ABS_Amt As Global.System.Nullable(Of Decimal)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_ABS_AmtChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_ABS_AmtChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Ent_By in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Ent_By() As String
        Get
            Return Me._VD_Ent_By
        End Get
        Set
            Me.OnVD_Ent_ByChanging(value)
            Me.ReportPropertyChanging("VD_Ent_By")
            Me._VD_Ent_By = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Ent_By")
            Me.OnVD_Ent_ByChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Ent_By As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Ent_ByChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Ent_ByChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Ent_Dt in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Ent_Dt() As Global.System.Nullable(Of Date)
        Get
            Return Me._VD_Ent_Dt
        End Get
        Set
            Me.OnVD_Ent_DtChanging(value)
            Me.ReportPropertyChanging("VD_Ent_Dt")
            Me._VD_Ent_Dt = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("VD_Ent_Dt")
            Me.OnVD_Ent_DtChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Ent_Dt As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Ent_DtChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Ent_DtChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Upd_By in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Upd_By() As String
        Get
            Return Me._VD_Upd_By
        End Get
        Set
            Me.OnVD_Upd_ByChanging(value)
            Me.ReportPropertyChanging("VD_Upd_By")
            Me._VD_Upd_By = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Upd_By")
            Me.OnVD_Upd_ByChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Upd_By As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Upd_ByChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Upd_ByChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Upd_Dt in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Upd_Dt() As Global.System.Nullable(Of Date)
        Get
            Return Me._VD_Upd_Dt
        End Get
        Set
            Me.OnVD_Upd_DtChanging(value)
            Me.ReportPropertyChanging("VD_Upd_Dt")
            Me._VD_Upd_Dt = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("VD_Upd_Dt")
            Me.OnVD_Upd_DtChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Upd_Dt As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Upd_DtChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Upd_DtChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Conf_By in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Conf_By() As String
        Get
            Return Me._VD_Conf_By
        End Get
        Set
            Me.OnVD_Conf_ByChanging(value)
            Me.ReportPropertyChanging("VD_Conf_By")
            Me._VD_Conf_By = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("VD_Conf_By")
            Me.OnVD_Conf_ByChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Conf_By As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Conf_ByChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Conf_ByChanged()
        End Sub
    '''<summary>
    '''There are no comments for property VD_Conf_Dt in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VD_Conf_Dt() As Global.System.Nullable(Of Date)
        Get
            Return Me._VD_Conf_Dt
        End Get
        Set
            Me.OnVD_Conf_DtChanging(value)
            Me.ReportPropertyChanging("VD_Conf_Dt")
            Me._VD_Conf_Dt = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("VD_Conf_Dt")
            Me.OnVD_Conf_DtChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VD_Conf_Dt As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Conf_DtChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVD_Conf_DtChanged()
        End Sub
End Class
